name: 'local_demo'
version: '1.0.0'
profile: 'local_demo'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

# Configuring models
models:
  local_demo:
    staging:
      +materialized: view
    intermediate:
      +materialized: ephemeral # hoặc view
    marts:
      +materialized: table
