name: 'local_demo'
version: '1.0.0'
profile: 'local_demo'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

# Configuring models
models:
  local_demo: # Tên project khai báo ở dòng 1
    # Cấu hình cho thư mục card (theo hình của bạn)
    card:
      staging:
        +materialized: view      # Staging nên là view để tiết kiệm bộ nhớ
      intermediate:
        +materialized: ephemeral # Hoặc view, tùy vào độ phức tạp của logic
      marts:
        +materialized: table     # Marts nên là table để BI tool load nhanh
